apiVersion: skaffold/v2beta3
kind: Config

profiles:
  - name: dev
    activation:
      - kubeContext: minikube
        command: dev
    build:
      artifacts:
        - image: web-server
          context: .
          docker:
            dockerfile: Dockerfile
          sync:
            infer:
              - src/**/*
      local:
        push: false

    deploy:
      kustomize:
        paths:
          - ./k8s/dev
  - name: prod
    activation:
      - kubeContext: gke_scihive-prod_us-central1_scihive-prod-gke
        command: dev
    build:
      googleCloudBuild: 
        projectId: scihive-prod
      artifacts:
        - image: gcr.io/scihive-prod/web-server
          context: .
          docker:
            dockerfile: Dockerfile
    deploy:
      statusCheckDeadlineSeconds: 600
      kustomize:
        paths:
          - ./k8s/prod

portForward:
  - resourceType: Service
    resourceName: web-server
    namespace: scihive-backend
    port: 5000
    localPort: 5000
  - resourceType: Service
    resourceName: postgres
    namespace: scihive-backend
    port: 5433
    localPort: 5432
