"""empty message

Revision ID: 3a87f31da4ef
Revises: 
Create Date: 2020-05-31 11:07:42.846446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a87f31da4ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('uploaded_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'paper', 'user', ['uploaded_by_id'], ['id'])
    op.add_column('paper_version', sa.Column('uploaded_by_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_version', 'uploaded_by_id')
    op.drop_constraint(None, 'paper', type_='foreignkey')
    op.drop_column('paper', 'uploaded_by_id')
    # ### end Alembic commands ###
