"""empty message

Revision ID: 79420dcea6cb
Revises: 6781303715b5
Create Date: 2020-10-22 13:56:39.438001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79420dcea6cb'
down_revision = '6781303715b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('metadata_state', sa.Enum('missing', 'fetching', 'error', 'ready', name='metadatastate'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'metadata_state')
    # ### end Alembic commands ###
