"""empty message

Revision ID: 89db7ce504c3
Revises: 6280e737c778
Create Date: 2020-11-01 13:15:22.406479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89db7ce504c3'
down_revision = '6280e737c778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('table_of_contents', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'table_of_contents')
    # ### end Alembic commands ###
