"""empty message

Revision ID: f455bbf24a68
Revises: 89db7ce504c3
Create Date: 2020-11-03 15:02:54.227273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f455bbf24a68'
down_revision = '89db7ce504c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('metadata_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'metadata_version')
    # ### end Alembic commands ###
